version: "3"

services:
  backend:
    network_mode: bridge
    image: node:slim
    volumes:
      - ./backend:/backend
    working_dir: /backend
    ports:
      - 5000:5000
    command: sh -c "npm i --quiet && npm start"

  frontend:
    network_mode: bridge
    image: node:slim
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    ports:
      - 3000:3000
    command: sh -c "npm i --quiet && npm start"
    depends_on:
      - backend
    